### ISSUE TITLE
Socratic Seminar 17 Reading List (June 2023)

### ISSUE THREAD

**Issue by satsie** [0xBEEFCAF3/bostonbitdevs#22] opened 2023-05-29 14:34 UTC
June BitDevs will be on Tuesday 6/13: https://www.meetup.com/boston-bitdevs/events/293840048/

Drop links here for the reading list!

**Comment by thomaznas** [comment] 2023-05-30 14:26
How about revisiting [TBDxxx is now Ark](https://www.arkpill.me/) ?

**Comment by DanGould** [comment] 2023-06-06 14:35
"A  mysterious deep-pocketed collector is looting uncommon ordinal sats from Binance and OKX ... the collector has committed at least 160 BTC of capital to this endeavor." https://twitter.com/mononautical/status/1666079581374230529

**Comment by 0xBEEFCAF3** [comment] 2023-06-06 19:15
https://github.com/bitcoin/bitcoin/pull/27827

**Comment by 0xBEEFCAF3** [comment] 2023-06-06 19:19
The curious case of the
half-half Bitcoin ECDSA nonces
https://eprint.iacr.org/2023/841.pdf

**Comment by 0xBEEFCAF3** [comment] 2023-06-08 13:13
More Ark explanations: https://gist.github.com/RubenSomsen/a394beb1dea9e47e981216768e007454

**Comment by thomaznas** [comment] 2023-06-08 14:59
This write-up was really helpful. I read the deep dive and had to listen to
the Stephan Liveira podcast episode several times to wrap my head around
this protocol (and I'm still grasping more and more details as I read more
stuff).

In this write-up, there is a statement that brought me some confusion - "The
main downside is reduced liquidity - the coins the Server receives back
won't be available to them immediately, so the faster coins move hands, the
more of S's liquidity becomes locked up.". I thought that every coinjoin
transaction (pool transactions) would spend the previous coinjoin round
transaction, and thus additional ASP/Server liquidity wouldn't be
necessary.

Best regards,

Thomaz

**Comment by 0xBEEFCAF3** [comment] 2023-06-12 21:48
@thomaznas Others definitely share the same confusion
https://twitter.com/rot13maxi/status/1667963452168499201

 My understanding is that the ASPs have to front the liquidity for each transfer. Overall there seems to be a higher liquidity requirement

**Comment by 0xBEEFCAF3** [comment] 2023-06-12 21:50
>ASP funds the coinjoin with their own on-chain funds in exchange for vTXOs redemptions. Therefore, the coinjoin transaction that hits on-chain has only one or a few inputs provided by the ASP. 

From https://www.arkpill.me/deep-dive

**Comment by DanGould** [comment] 2023-06-13 01:09
## Silent Payments BIP vs 

### Interaction (req / response)

Literally just respono with a new address on tha web (Gap limit, liveliness are problems)

### XPub Sharing

Each person needs to get that xpub out of band & respect Gap Limit

### BIP 47

BIP47's tradeoffs:
1. There's an on-chain footprint that can easily leak privacy, you link a UTXO to an identity "notification TX"
2. The recipient learns who the sender is (imagine you donate to a sensitive cause and the cause leaks this info)
- Notification TX OP_RETURN output includes the payment code of the sender, a unique identifier for the transaction, and the message intended for the receiver.
3. Current implementations leak full privacy to a trusted server
  - Run a Dojo? We currently have an open PR for Bitcoin Core to add support for Silent Payments, so any wallet that supports connecting to full nodes could then trivially support Silent Payments, gaining all benefits.

**Comment by 0xBEEFCAF3** [comment] 2023-06-13 01:12
[bitcoin-dev] Bitcoin Transaction Relay over Nostr
https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2023-May/021700.html

**Comment by DanGould** [comment] 2023-06-13 01:23
Payjoin over Nostr

https://twitter.com/1440000bytes/status/1666115243481907200?s=20

https://twitter.com/nobsbitcoin/status/1668316231139459082

**Comment by DanGould** [comment] 2023-06-13 01:44
[BitMask had it's first (afaik) mainnet beta release](https://stacker.news/items/190121) which led to a spontaneous AMA with Director of Eng [@cryptoquick](https://stacker.news/cryptoquick). The headlining wizbang of [Diba](https://diba.io/)'s Bitcoin wallet browser extension is storing "unique digital assets" issued with the [RGB protocol](https://www.rgbfaq.com/faq/what-is-rgb).
[BitMask Wallet 0.6 Beta. With support for Mainnet, Taproot, RGB 0.10, Carbonado \ 27 comments](https://stacker.news/items/190121)

The US government was fashionably late to their own "Are Cryptohs Securities?" reveal party charging [Coinbase for Operating as an Unregistered Securities Exchange, Broker, and Clearing Agency](https://www.sec.gov/news/press-release/2023-102).
[SEC Charges Coinbase for Operating as an Unregistered Securities Exchange \ 40 comments](https://stacker.news/items/188854)
[www.sec.gov/news/press-release/2023-102](http://www.sec.gov/news/press-release/2023-102)

Mass Adoption Freedom Festival https://massadoption.net/freedomfest.html

**Comment by 0xBEEFCAF3** [comment] 2023-06-13 13:54
LNDK
https://www.nobsbitcoin.com/lndk/

**Comment by sutt** [comment] 2023-06-13 21:20
Interested in walking through this docker/LND tutorial with friends: https://github.com/cmdruid/docker-workshop

**Comment by sutt** [comment] 2023-06-13 21:23
And Making StableDiffusion QR codes for LN-StaticInvoices: https://stable-diffusion-art.com/qr-code/

**Closed** 2023-06-16 14:49 UTC
